### ISSUE TITLE
Custom stylesheets don't work in 1.0.0

### ISSUE THREAD

**Issue by jbartok** [adamko-dev/dokkatoo#43]
We are using Dokkatoo at Gradle to generate Kotlin DSL reference docs, see here:
* https://github.com/gradle/gradle/pull/24302

Everything was fine on version `0.0.4` of the plugin, but now, after upgrading to `1.0.0`, I can't get the custom stylesheets and assets to work. I think I'm using them as advertised in the documentation, see [here](https://github.com/gradle/gradle/blob/af224506c8a5c460f78e1df93d435039b756a34f/build-logic/documentation/src/main/groovy/gradlebuild/docs/GradleKotlinDslReferencePlugin.java#L95).

In general, any feedback on our attempts is welcome.

**Comment by aSemy** [comment]
Thanks for the report! I'll take a closer look.

My first guess is that you're adding a custom CSS file:

https://github.com/gradle/gradle/blob/af224506c8a5c460f78e1df93d435039b756a34f/build-logic/documentation/src/main/groovy/gradlebuild/docs/GradleKotlinDslReferencePlugin.java#L50

But custom files aren't automatically loaded by Dokka.

> [It's also possible to override Dokka's default stylesheets by providing files with the same name](https://kotlinlang.org/docs/dokka-html.html#customize-styles)

The easiest way is to override some CSS that already exists.

https://github.com/adamko-dev/dokkatoo/blob/693eeaa5900f77acb1fe7e9376d8fb3463fdd597/docs/build.gradle.kts#L17C3-L25

I'm not sure why it might have worked in 0.0.4 but not in 1.0.0 though...

**Comment by aSemy** [comment]
I've discussed this with @jbartok and it's working now. There were two problems with the config:

1. Just because files are added into `customStyleSheets` or `customAssets`, it doesn't mean Dokka will automatically load them. The properties are just used by Dokka to determine where the files should be placed into the assembled publication - nothing more. 
  
  Dokka's recommended approach to make sure the CSS files are loaded by the HTML are to use the same file names (e.g. `logo-styles.css`, so that they will *overwrite* Dokka's default files).
2. Any relative paths need to be relative *after* the publication is assembled, which can be misleading. It's best to try and mirror Dokka's directory structure in the source files, which can help IDE inspections.

To try and improve this, I'll add some more KDoc on the properties.

* "Dokka will not load arbitrary stylesheet files. Try overwriting existing files... $linkToDokkaDocs" 
* "Relative paths must..."

**Comment by jbartok** [comment]
@aSemy please check out our latest PR, seems like custom stylesheet filenames do work after all

**Comment by aSemy** [comment]
Ah, thanks for the update. It's a good thing that I didn't start updating the docs yet.

**Comment by aSemy** [comment]
additional KDoc added 

https://github.com/adamko-dev/dokkatoo/commit/0359bc5f6efee08f684663d4aff502b5cb20503e
