### ISSUE TITLE
Publish to MavenCentral?

### ISSUE THREAD

**Issue by martinbonnin** [adamko-dev/dokkatoo#61]
Would you consider publishing the plugin to Maven Central? Gradle Plugin Portal works too but having it in Maven Central would make it more discoverable when used in convention plugins, etc... ?

**Comment by aSemy** [comment]
Thanks for the request, I totally agree! Publishing to Maven Central would be a solid improvement.

However, I've had a lot of trouble trying to make Gradle + Signing + Maven Central work in other projects, so I've been avoiding it. The ease of the Gradle Plugin Portal is a breath of fresh air in comparison! 

Do you know how to best set up Maven Central publishing? Do you want to make a PR?

I know there are helper plugins like https://github.com/gradle-nexus/publish-plugin, but I don't like that they use discouraged techniques like `afterEvaluate {}` and `allprojects {}`, so I want to avoid them.

**Comment by martinbonnin** [comment]
👍 I can look into that. No promises but feel free to assign it to me.

**Comment by aSemy** [comment]
The Gradle config should probably be similar to how I set it up in Kotka Streams

* https://github.com/adamko-dev/kotka-streams/pull/32/files 
* https://github.com/adamko-dev/kotka-streams/blob/37b6427e975f1dd835ee91387024478500b43796/buildSrc/src/main/kotlin/buildsrc/convention/maven-publish.gradle.kts

Which ended up working for snapshots, but I didn't finish it and get regular publishing working.

I'll take a look at copying over this over and cc you into the PR.

Related to this, I'd like the project version number to be easier to update. Currently updating the version requires running a Gradle task to update the Dokkatoo version in all of the examples and tests, and the committing the update ([example](https://github.com/adamko-dev/dokkatoo/commit/d9eb584d99df1b12bdf17d127573ce703792d665)). I'm wary about automating a commit in a pipeline, because I want to manually verify the versions are updated correctly. Maybe there's a way of setting up a GitHub Workflow that creates a PR with the changes... just thinking out loud 🤔

**Comment by martinbonnin** [comment]
> Currently updating the version requires running a Gradle task to update the Dokkatoo version in all of the examples and tests

Wouldn't updating the root version automatically update all child module thanks to some classloader magic? I even believe it's more efficient that way cause it's loading the plugin classes only once?

**Comment by hfhbd** [comment]
Just curios regarding the nexus-plugin and your own publishing implementation: How do you create a staging repository and close it?

**Comment by martinbonnin** [comment]
@hfhbd There's a REST API for it. It's not super well documented but you can look at this: https://github.com/martinbonnin/vespene/blob/main/vespene-lib/src/main/kotlin/net/mbonnin/vespene/lib/NexusStagingApi.kt#L31

**Comment by aSemy** [comment]
I've tried adding Maven Central publishing in https://github.com/adamko-dev/dokkatoo/pull/116, but unfortunately the Gradle Plugin Publish Plugin causes too many issues, so this issue is blocked until Gradle can provide something that works.

**Comment by aSemy** [comment]
I've managed to get Maven Central publishing working! 

https://s01.oss.sonatype.org/content/repositories/releases/dev/adamko/dokkatoo/dokkatoo-plugin/
