### ISSUE TITLE
"Build javadoc.jar" docs out of date?

### ISSUE THREAD

**Issue by sschuberth** [adamko-dev/dokkatoo#70]
Are the docs at https://kotlinlang.org/docs/dokka-gradle.html#build-javadoc-jar outdated? I cannot seem to find a task named `dokkaHtml` or `dokkaJavadoc`. Are these "wrapper tasks" even still needed, or are they built-in as `dokkatooGenerateModuleHtml` and `dokkatooGenerateModuleJavadoc` respectively by now?

**Comment by sschuberth** [comment]
> Are these "wrapper tasks" even still needed, or are they built-in as `dokkatooGenerateModuleHtml` and `dokkatooGenerateModuleJavadoc` respectively by now?

I can answer this bit myself, the tasks are still needed. The word "module" does not refer to a module in the Maven artifact sense, but to a Java module.

**Comment by aSemy** [comment]
Hi 👋

The docs on kotlinlang.org aren't outdated, but instead are for [the official Dokka Gradle Plugin](https://github.com/Kotlin/dokka/tree/master/runners/gradle-plugin). Dokkatoo is a completely separate implementation of a Gradle plugin that, under the hood, uses [Dokka Generator](https://github.com/Kotlin/dokka/blob/master/core/src/main/kotlin/DokkaGenerator.kt) to generate documentation.

If you're using Dokkatoo then use the output of the `dokkatooGeneratePublicationHtml` task to build a Javadoc JAR.

> The word "module" does not refer to a module in the Maven artifact sense, but to a Java module.

I'm not familiar with Java modules, so I'll re-explain and hopefully that makes it more clear for both of us.

First, a bit of explanation about Dokka Generator. When it comes to building a final HTML site from multiple subproject, Dokka Generator works in stages. 

1. First it generates a 'partial' site, by setting `delayTemplateSubstitution` to `true`. These partial sites are missing some additional steps, like finalising the HTML links between all the different classes. 
   
    In the Dokka Gradle Plugin, this is what the 'partial' tasks do. In Dokkatoo, it's the 'module' tasks. (_Should I have named the Dokkatoo tasks to match the Dokka Gradle Plugin tasks? Maybe..._)

2. In the second step, all of the partial sites are combined together into a final publication (by running Dokka Generator with setting `delayTemplateSubstitution` to `false`). In this phase links between classes are computed since all the 'partials' from all subprojects are in one place).
   
    In the Dokka Gradle Plugin, this is what the `dokka<format>` tasks do. In Dokkatoo, it's the 'dokkatooGeneratePublication<format>' tasks.

**Comment by sschuberth** [comment]
Thanks for the clarifications. I indeed didn't realize the transition from dokkatoo to dokka docs when following some links. All good now!
