### ISSUE TITLE
Add a contributing guide

### ISSUE THREAD

**Issue by EdricChan03** [adamko-dev/dokkatoo#72]
A contributing guide for this repository would be ideal for first-time contributors (e.g. how to set up the project for local development, adding new features, navigating around the codebase, commit guidelines, etc), and also standardises project conventions/rules (if any) for existing contributors.

**Comment by aSemy** [comment]
I totally agree that more documentation is necessary, so if you want to see something specific feel free to propose it. While I could write loads of docs, I suspect that I'd write a lot of words that no one would read :)


I'm a bit concerned that any documentation would just become out of date (unless it was tested using Knit or something, but that's also additional work/overhead).

Also, keep in mind that this project has a tenuous future. The aim is to merge into the main Dokka repo, so it's a good idea to try and keep the projects aligned, and also be aware that any work might be removed during this potential merge.

> how to set up the project for local development

Just checking it out and running `./gradlew build` or `./gradlew check` should work fine

> adding new features

It's usually better to make an issue first, rather than a PR. This would help getting the purpose clear, or to prevent double work. However, I think sometimes a PR-first approach can be helpful to demonstrate the end result.

> navigating around the codebase

What sort of docs would help with navigating? Is there something in particular you had in mind?

> commit guidelines

I've enabled squash commits on the PRs, and that's all I really care about.
