### ISSUE TITLE
Published Javadocs are empty

### ISSUE THREAD

**Issue by EdricChan03** [adamko-dev/dokkatoo#98]
It appears that the javadoc.jar file served at the [Gradle Plugin Portal](https://plugins.gradle.org/m2/dev/adamko/dokkatoo/dokkatoo-plugin/1.5.0/) is empty when extracted - is this intentional?

**Comment by aSemy** [comment]
Dokkatoo doesn't intentionally publish a Javadoc JAR. I guess it's enabled automatically by `java-gradle-plugin`, and since there are no Java sources it's empty.

A Javadoc JAR (even if it's empty) might be required by the Gradle Plugin Portal? I know that Maven Central requires a Javadoc JAR (again, even if it's empty) (related: #61).

If it were up to me, I wouldn't publish one at all! The sources JAR should be superior to a Javadoc JAR, since the source code is visible within IDEs. If Dokka were more performant (e.g. https://github.com/Kotlin/dokka/issues/1405) then I could be persuaded to generate a Javadoc site for the Javadoc JAR, but at the moment I'd rather not.

Can you explain more about why you are asking? Were you just double checking? Is the Javadoc JAR required for something?

**Comment by EdricChan03** [comment]
> Can you explain more about why you are asking? Were you just double checking? Is the Javadoc JAR required for something?

Just curious, unrelated checking when looking into publishing Javadocs for an Android library
